# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  rpg:
    image: rpg
    build:
      context: .
      dockerfile: RPG/Dockerfile
    ports:
      - 5149:5149
