# curl -X 'GET' \
#     'https://localhost:7188/WeatherForecast/factory_method_order_pizza' \
#     -H 'accept: */*'

curl -X 'GET' \
    'https://localhost:7188/WeatherForecast/iterator_test' \
    -H 'accept: */*'